config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:new, :create, :show, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% else %>
  <p>投稿もしくはユーザーをフォローしてみましょう</p>  
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-follow" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
  </div>
<% end %>

app/views/shared/_header_humburger.html.erb
 <label for="memu" class="close">×</label>
 <% if logged_in? %>
      <div class="search-form">
        <%= render 'shared/search' %>
      </div>
    <% end %>
    <nav>
      <ul class="nav flex-column">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "投稿", new_micropost_path %></li>
          <li><%= link_to "ユーザー", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to current_user do %>
                  <i class="far fa-user-circle"></i> プロフィール
                <% end %>
              </li>
              <li>
                <%= link_to notifications_path(current_user) do %>
                  <i class="far fa-bell"></i> 通知
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_path(current_user) do %>
                  <i class="fas fa-sliders-h"></i> 設定
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "新規登録", signup_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>

app/views/shared/_search.html.erb
<%= form_tag(yield(:path), method: :get, class: "input-group") do %>
  <%= text_field_tag :search, params[:search], placeholder: "検索", class: 'form-control' %>
  <span class="input-group-btn">
    <%= button_tag sanitize('<i class="fa fa-search" aria-hidden="true"></i>'), :type => "submit", :name => nil, class: "btn" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<ul class="stats">
  <li>
    <span>
      投稿
      <span><%= @user.microposts.count %></span>
      件
    </span>
  </li>
  <li>
    <a href="<%= following_user_path(@user) %>">
      フォロー中
      <span id="following" class="stat"><%= @user.following.count %></span>
      人
    </a>
  </li>
  <li>
    <a href="<%= followers_user_path(@user) %>">
      フォロワー
      <span id="followers" class="stat"><%= @user.followers.count %></span>
      人
    </a>
  </li>
</ul>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-unfollow" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>