config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:new, :create, :show, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  attr_accessor :picture_cache
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  mount_uploader :img, PictureUploader
  validates :user_id, presence: true
  validates :picture, presence: true
  validates :content, length: { maximum: 140 }
  validate  :picture_size
  
  def self.search(search)
    if search
      where(['content LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def new
    @micropost  = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'index'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @micropost = Micropost.find_by(id: params[:id])
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private

    def micropost_params
      params.require(:micropost).permit(:picture, :content)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li class="micropost" id="micropost-<%= micropost.id %>">
  <div class="coordination">
    <%= link_to micropost do %>
      <%= image_tag micropost.picture.url if micropost.picture? %>
    <% end %>
  </div>
  <% unless request.path.include?("users") %>
    <div class="profile">
      <div class="profile__top">
        <div class="profile__top--img">
          <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
        </div>
        <div class="profile__top--name">
          <p><%= micropost.user.name %></p>
        </div>
      </div>
      <div class="profile__bottom">
        <div class="datetime">
         <p><i class="far fa-clock"></i> <%= micropost.created_at.to_s(:datetime_jp) %></p>
        </div>
      </div>
    </div>
  <% end %>
</li>

app/views/microposts/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="micropost_btn">
    <%= f.submit "✔", class: "btn" %>
  </div>
  <div class="micropost_pick">
    <div class="micropost_pick__picture">
      <%= f.file_field :picture,  accept: 'image/jpeg,image/gif,image/png', class: "btn" %>
    </div>
    <div class="micropost_pick__content">
      <%= f.text_area :content, placeholder: "どんなコーディネートを組んだ？" %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/index.html.erb
<% provide(:title, 'Post') %>
<% provide(:path, microposts_path) %>

<div class="row">
  <aside class="col-md-12">
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
</div>

app/views/microposts/new.html.erb
<% provide(:title, 'Post') %>
<% provide(:path, new_micropost_path) %>

<div class="row no-gutters">
  <div class="col-md-12">
    <div id="info">
      <div class="crim sec-ttl">
        NEW POST
        <span class="bar"></span>
      </div>
    </div>
    <div class="micropost_form">
      <%= render 'micropost_form' %>
    </div>
  </div>
</div>

app/views/microposts/show.html.erb
<div class="row no-gutters">
  <aside class="col-md-12">
    <div class="user_info">
      <div class="row no-gutters">
        <div class="col-md-4">
          <div class="user_info_left">
            <%= link_to gravatar_for @micropost.user %>　<!-- ユーザー写真 -->
          </div>
        </div>
        <div class="col-md-8">
          <section class="user_info_right">
            <div class="user_info_right__top">
              <h2><%= @micropost.user.name %></h2>　<!-- ユーザー名 -->
              <%= render 'shared/follow_form' if logged_in? %>　<!-- フォローボタン -->
            </div>
            <%= render 'shared/stats' %>  <!-- 統計 -->
          </section>
        </div>
      </div>
    </div>
  </aside>
      <div class="col-md-6">
        <div class="details_main">
          <div class="details_img">
            <p><%= image_tag @micropost.picture.url if @micropost.picture? %></p>
          </div>
          <div class="details_info">
                
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="details_sub">
          <div class="img_content">
            <p><%= @micropost.content %></p>    
          </div>
          <div class="img_content_bottom">
            <div class="datetime">
              <p><i class="far fa-clock"></i> <%= @micropost.created_at.to_s(:datetime_jp) %></p>
            </div>
            <% if current_user?(@micropost.user) %>
              <%= link_to @micropost, method: :delete, data: { confirm: "You sure?" } do %>
                <i class="fas fa-trash-alt delete"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
</div>