config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:new, :create, :show, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <div class="ttl crim">
      <%= link_to "SNAP MARKET", root_path, id: "logo" %>
    </div>
  </small>
  <nav class="crim">
    <ul>
      <li><%= link_to "ABOUT", about_path %></li>
      <li><%= link_to "HELP", help_path %></li>
      <li><%= link_to "CONTACT", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">NEWS</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div id="appHeader"class="container">
    <div class="crim">
      <%= link_to "SNAP MARKET", root_path, id: "logo" %>
    </div>
    <div class="none_humburger" >
      <% if logged_in? %>
        <div class="search-form">
          <%= render 'shared/search' %>
        </div>
      <% end %>
      <nav class="crim">
        <ul>
          <li><%= link_to "HOME", root_path %></li>
          <% if logged_in? %>
            <li><%= link_to "NEW POST", new_micropost_path %></li>
            <li><%= link_to "USER", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                ACCOUNT<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to current_user do %>
                    <i class="far fa-user-circle"></i>PROFILE
                  <% end %>
                </li>
                <li>
                  <%= link_to notifications_path(current_user) do %>
                    <i class="far fa-bell"></i> NOTIFICATION
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <i class="fas fa-sliders-h"></i> SETTING
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "LOG OUT", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "SIGN UP", signup_path %></li>
            <li><%= link_to "LOG IN", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <!--<div id="humburger">-->
    <!--  <input id="memu" type="checkbox" />-->
    <!--  <label for="memu" class="open">〇</label>-->
    <!--   render 'shared/header_humburger' -->
    <!--</div>-->
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>